recollindex -c /archivedata/mail-archive-compress/2011_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2011_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2012_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2013_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2014_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2015_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2016_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2017_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2018_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2019_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2020_12/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_01/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_02/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_03/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_04/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_05/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_06/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_07/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_08/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_09/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_10/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_11/indexdata/
recollindex -c /archivedata/mail-archive-compress/2021_12/indexdata/
