<?php
deepen@technoinfotech.com:info@technoinfotech.com
sanjay@technoinfotech.com:info@technoinfotech.com
deepen@technoinfotech.com:cloud@technoinfotech.com
sanjay@technoinfotech.com:cloud@technoinfotech.com
sanjay@technoinfotech.com:support@technoinfotech.com
sanjay@technoinfotech.com:support@technoinfotech.com
nikhil.mehta@technogroup.co.in:alerts@office.clubemerald.in
nikhil.mehta@technogroup.co.in:pos.reports@clubemerald.in
nikhil.mehta@technogroup.co.in:pmsreports@clubemerald.in
nikhil.mehta@technogroup.co.in:accountsmanager@clubemerald.in
nikhil.mehta@technogroup.co.in:accounts@clubemerald.in
nikhil.mehta@technogroup.co.in:nikhil.mehta@clubemerald.in
nikhil.mehta@technogroup.co.in:technosh@technogroup.co.in
nikhil.mehta@technogroup.co.in:technosh@bom5.vsnl.net.in
nikhil.mehta@technogroup.co.in:technosh@vsnl.com
nikhil.mehta@technogroup.co.in:tbfspl@technogroup.co.in
nikhil.mehta@technogroup.co.in:noshow@clubemerald.in
nikhil.mehta@technogroup.co.in:clubstaff@clubemerald.in
nikhil.mehta@technogroup.co.in:info@clubemerald.in
nikhil.mehta@technogroup.co.in:info@apteindia.com
nikhil.mehta@technogroup.co.in:personal.axis@technogroup.co.in
nikhil.mehta@technogroup.co.in:personal@technogroup.co.in
nikhil.mehta@technogroup.co.in:jaydeep.mehta@technogroup.co.in
generalmanager@clubemerald.in:pmsreports@clubemerald.in
fom@clubemerald.in:pmsreports@clubemerald.in
accounts7@clubemerald.in:banquetmanager@clubemerald.in
accounts7@clubemerald.in:banquets@clubemerald.in
accounts7@clubemerald.in:banquetsales@clubemerald.in

?>
